package DBRepositorio;

import java.util.List;

/**
 * @author Leonidas Garcia Lescano
 * @param <T>
 */
// TANTA WEBADA PARA QUE LA CLASE ABSTRACTA SOLO TENGA ESTO? EEEHH CI
// UNA CLASE ABSTRACTA ES ALGO ASI COMO CONJUNTO DE INSTRUCCIONES QUE DEFINEN QUE ES LO QUE DEBE TENER UNA CLASE
// PERO NO COMO DEBE TENERLO.
// POR EJEMPLO, CHECATE LIBROS Y MONOGRAFIAS (AMBOS HEREDAN DE ENTIDADES) Y MIRA SU METODO TOARRAY. AMBOS LO TIENEN, SI, PERO
// LO IMPLEMENTAN DE FORMAS DISTINTAS, QUEDA MAS CLARO? NO? GEPETEA P TIO, DE DONDE XUXA CREES QUE APRENDI TODO LO QUE SE?
public abstract class Entidades {

    public abstract Object[] toArray();
}
